version: "3"

services:
  mc:
    image: itzg/minecraft-server:multiarch
    container_name: "${APP_CONTAINER_NAME}"
    ports:
      - ${SERVER_PORT}:25565
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      VERSION: "${VERSION}"
      GENERIC_PACK: "${GENERIC_PACK}"
      CF_SERVER_MOD: "${CF_SERVER_MOD}"
      OVERRIDE_SERVER_PROPERTIES: "${OVERRIDE_SERVER_PROPERTIES}"
      MOTD: "${MOTD}"
      DIFFICULTY: "${DIFFICULTY}"
      ENFORCE_WHITELIST: "${ENFORCE_WHITELIST}"
      WHITELIST_FILE: "${WHITELIST_FILE}"
      OPS_FILE: "${OPS_FILE}"
      ENABLE_RCON: "${ENABLE_RCON}"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      ENABLE_QUERY: "${ENABLE_QUERY}"
      MAX_PLAYERS: "${MAX_PLAYERS}"
      #MAX_WORLD_SIZE: "${MAX_WORLD_SIZE}"
      ALLOW_NETHER: "${ALLOW_NETHER}"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "${ANNOUNCE_PLAYER_ACHIEVEMENTS}"
      #ENABLE_COMMAND_BLOCK: "${ENABLE_COMMAND_BLOCK}"
      #FORCE_GAMEMODE: "${FORCE_GAMEMODE}"
      GENERATE_STRUCTURES: "${GENERATE_STRUCTURES}"
      HARDCORE: "${HARDCORE}"
      SNOOPER_ENABLED: "${SNOOPER_ENABLED}"
      #MAX_BUILD_HEIGHT: "${MAX_BUILD_HEIGHT}"
      VIEW_DISTANCE: "${VIEW_DISTANCE}"
      #SEED: "${SEED}"
      MODE: "${MODE}"
      PVP: "${PVP}"
      ONLINE_MODE: "${ONLINE_MODE}"
      ALLOW_FLIGHT: "${ALLOW_FLIGHT}"
      SERVER_NAME: "${SERVER_NAME}"
      SERVER_PORT: "${SERVER_PORT}"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - ${DATA_PATH}/data:/data
    # all mods in this directory get copied into /data/mods at startup
    - ${DATA_PATH}/mods:/mods:ro
